#cloud-config
users: #User die auf der VM erstellt werden sollen
  - name: ubuntu #User name
    sudo: ALL=(ALL) NOPASSWD:ALL #SUDO Rules
    groups: users, admin # Benutzergruppen, zu denen der Benutzer gehört
    home: /home/ubuntu #Pfad zum Home verzeichnis. Wenn der User "cd ~" ausführt geht er zu diesem Pfad
    shell: /bin/bash #Definiert dass Bash als Shell verwendet werden sollte.
    ssh_authorized_keys: #SSH Public Keys
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCLgKfWNz6ZttN5QGOBbD3H9zMlLSE7aHZhjaKNTfz+H604Lv5l1De+3rDLXB9/JXm7xJt64FJNUEUhQwOES/7JkHz4gSZKuOsHAWBgzsUxGZHak5wrn7QK1Cq4xdvn0VCS1YtrA7ybyVr7tr0x7XTCi+0bP2Yj/kGQjioukhTAC54EcVVRxSdfTIDV+3T/SyD1G7Hyrstu8HzSokU9YQHzc7Y83w2oa9l+xsQZOAjSiXhYYRGk+uyDHarDE95jaq65hx+kHjTdE6bYQXRvSyoKGJF50ST9mWP26FxD1vCOp1oULU6tF4RFtUcBqETS/BX00uEIl17RxIgGdek0he7T aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false #Erlaubt den Usern die Verbindung mit einem Passwort über SSH zu machen. Falls false nur Public/Private Key Methode wäre erlaubt
disable_root: false #Login als Root User über SSH ist erlaubt
package_update: true #Updates werden installiert
packages: #Packages die auf der Machine installiert werden sollten
  - apache2
  - curl
  - wget
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer
runcmd: #Befehle die nach dem Start der VM ausgeführt werden sollen
  - sudo a2enconf adminer
  - sudo systemctl restart apache2
write_files: #Dateien die auf der VM erstellt werden sollen
  - path: /var/www/html/db.php
    content: |
      <?php
          //database
          $servername = "54.89.55.138";
          $username = "admin";
          $password = "password";
          $dbname = "mysql";

          // Create connection
          $conn = new mysqli($servername, $username, $password, $dbname);
          // Check connection
          if ($conn->connect_error) {
                  die("Connection failed: " . $conn->connect_error);
          }

          $sql = "select Host, User from mysql.user;";
          $result = $conn->query($sql);
          while($row = $result->fetch_assoc()){
                  echo($row["Host"] . " / " . $row["User"] . "<br />");
          }
          //var_dump($result);
      ?>
  - path: /var/www/html/info.php
    content: |
      <?php

      // Show all information, defaults to INFO_ALL
      phpinfo();

      ?>
