users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    lock_passwd: false
    plain_text_passwd: 'password'
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCLgKfWNz6ZttN5QGOBbD3H9zMlLSE7aHZhjaKNTfz+H604Lv5l1De+3rDLXB9/JXm7xJt64FJNUEUhQwOES/7JkHz4gSZKuOsHAWBgzsUxGZHak5wrn7QK1Cq4xdvn0VCS1YtrA7ybyVr7tr0x7XTCi+0bP2Yj/kGQjioukhTAC54EcVVRxSdfTIDV+3T/SyD1G7Hyrstu8HzSokU9YQHzc7Y83w2oa9l+xsQZOAjSiXhYYRGk+uyDHarDE95jaq65hx+kHjTdE6bYQXRvSyoKGJF50ST9mWP26FxD1vCOp1oULU6tF4RFtUcBqETS/BX00uEIl17RxIgGdek0he7T aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: false
disable_root: false
packages:
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php
  - php-mysqli
  - adminer

write_files:
  - content: |
      <?php
        // Show all information, defaults to INFO_ALL
        phpinfo();
      ?>
    path: /var/www/html/info.php
    owner: root:root
    permissions: '0644'

runcmd:
  - [sudo, a2enconf, adminer]
  - [sudo, systemctl, restart, apache2]
